In [1]:
list1=[1, "ali", 6.7] #list can have different data type

In [3]:
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [5]:
for i in list1:
    print(i)

1
ali
6.7


In [7]:
for i in list1:
    print(i)
    print(type(i))

1
<class 'int'>
ali
<class 'str'>
6.7
<class 'float'>


In [ ]:
!pip install numpy

In [9]:
import numpy

In [13]:
arr=numpy.array(list1)

In [15]:
arr


array(['1', 'ali', '6.7'], dtype='<U32')

In [18]:
for i in arr:
    print(i)
    print(type(i))

1
<class 'numpy.str_'>
ali
<class 'numpy.str_'>
6.7
<class 'numpy.str_'>


In [20]:
list1=[1,2,3,4,6,78,67]
sum(list1)

161

In [22]:
max(list1)

78

In [24]:
min(list1)

1

In [26]:
list1.append(78)

In [28]:
list1

[1, 2, 3, 4, 6, 78, 67, 78]

In [30]:
list1.extend([14,56,67])

In [32]:
list1

[1, 2, 3, 4, 6, 78, 67, 78, 14, 56, 67]

In [50]:
list1.sort(reverse=True)

TypeError: 'ascending' is an invalid keyword argument for sort()

In [36]:
list1

[1, 2, 3, 4, 6, 14, 56, 67, 67, 78, 78]

In [40]:
list1.remove(14)

In [42]:
list1

[1, 2, 3, 4, 6, 56, 67, 67, 78, 78]

In [44]:
list1.index(56)

5

In [46]:
list1[8]

78

In [58]:
list1.sort(reverse=True)
list1

[78, 78, 67, 67, 56, 6, 4, 3, 2, 1]

In [60]:
list1[1:5]
#1st value inclusive
#2nd argument exclusiv

[78, 67, 67, 56]

In [62]:
import numpy
arr1=numpy.array([2,4,57,8])

In [64]:
l1=[1,2,3,4]
l2=[8,9,0,5]

print(l1+l2)

[1, 2, 3, 4, 8, 9, 0, 5]


In [70]:
arr1=numpy.array([2,4,57,8])
arr2=numpy.array([5,6,7,8])

print(arr1+arr2)

[ 7 10 64 16]


In [72]:
import numpy as np

In [74]:
np.sum(arr1)

71

In [76]:
arr1=numpy.array([2,4,57,8])

In [78]:
arr1.shape

(4,)

In [80]:
arr1.ndim

1

In [82]:
array2d= np.array([[12,34,6],
                  [56,34,76]])

In [84]:
array2d.shape

(2, 3)

In [86]:
array2d.ndim

2

In [92]:
list1=[2,3,4,5,6,8,9,72]
list1.index(72)

7

In [96]:
list1[7]

72

In [98]:
list1[0:7]

[2, 3, 4, 5, 6, 8, 9]

In [100]:
array2d

array([[12, 34,  6],
       [56, 34, 76]])

In [102]:
np.sum(array2d)

218

In [104]:
np.mean(array2d)

36.333333333333336

In [106]:
np.median(array2d)

34.0

In [110]:
np.std(array2d)

24.094720491334932

In [ ]:
!pip install pandas
import pandas

In [114]:
import pandas as pd

In [118]:
data=pd.read_excel("D:\\test.xlsx")

In [120]:
data

name  marks   age
0       Ali   45.0  23.0
1     Ahmed  100.0  12.0
2    Rameen   34.0  34.0
3    Ayesha   23.0   0.0
4   Khadija    NaN  42.0
5    saleem   78.0   NaN
6     rehan   98.0  12.0
7    daneen   22.5  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0

In [124]:
data.head(3)

name  marks   age
0     Ali   45.0  23.0
1   Ahmed  100.0  12.0
2  Rameen   34.0  34.0

In [126]:
data.tail()

name  marks   age
5    saleem   78.0   NaN
6     rehan   98.0  12.0
7    daneen   22.5  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0

In [128]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    10 non-null     object 
 1   marks   9 non-null      float64
 2   age     9 non-null      float64
dtypes: float64(2), object(1)
memory usage: 372.0+ bytes


In [130]:
data.columns

Index(['name', 'marks', 'age'], dtype='object')

In [134]:
data.dtypes

name      object
marks    float64
age      float64
dtype: object

In [136]:
data.describe()

marks        age
count    9.000000   9.000000
mean    50.833333  20.000000
std     32.274216  14.739403
min     22.500000   0.000000
25%     23.000000  12.000000
50%     34.000000  21.000000
75%     78.000000  34.000000
max    100.000000  42.000000

In [140]:
data.isnull()

name  marks    age
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False   True  False
5  False  False   True
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [142]:
#data.fillna(0)


In [144]:
#data=data.dropna()
data.dropna(inplace=True)

In [146]:
data

name  marks   age
0       Ali   45.0  23.0
1     Ahmed  100.0  12.0
2    Rameen   34.0  34.0
3    Ayesha   23.0   0.0
6     rehan   98.0  12.0
7    daneen   22.5  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0

In [148]:
data["name"]

0         Ali
1       Ahmed
2      Rameen
3      Ayesha
6       rehan
7      daneen
8     zawiyar
9    abdullah
Name: name, dtype: object

In [150]:
for i in data["name"]:
    print(i)

Ali
Ahmed
Rameen
Ayesha
rehan
daneen
zawiyar
abdullah


In [154]:
int(4==3)

0

In [156]:
np.linspace(1,100, 1000)

array([  1.        ,   1.0990991 ,   1.1981982 ,   1.2972973 ,
         1.3963964 ,   1.4954955 ,   1.59459459,   1.69369369,
         1.79279279,   1.89189189,   1.99099099,   2.09009009,
         2.18918919,   2.28828829,   2.38738739,   2.48648649,
         2.58558559,   2.68468468,   2.78378378,   2.88288288,
         2.98198198,   3.08108108,   3.18018018,   3.27927928,
         3.37837838,   3.47747748,   3.57657658,   3.67567568,
         3.77477477,   3.87387387,   3.97297297,   4.07207207,
         4.17117117,   4.27027027,   4.36936937,   4.46846847,
         4.56756757,   4.66666667,   4.76576577,   4.86486486,
         4.96396396,   5.06306306,   5.16216216,   5.26126126,
         5.36036036,   5.45945946,   5.55855856,   5.65765766,
         5.75675676,   5.85585586,   5.95495495,   6.05405405,
         6.15315315,   6.25225225,   6.35135135,   6.45045045,
         6.54954955,   6.64864865,   6.74774775,   6.84684685,
         6.94594595,   7.04504505,   7.14414414,   7.24

In [158]:
df=pd.read_excel("test.xlsx")