In [ ]:
!pip install numpy

In [1]:
import numpy

In [9]:
list1=[1, "ali", 7.8]

In [5]:
for i in range(5):
    print(i)

0
1
2
3
4


In [13]:
for i in list1:
    print(i)
    print(type(i))

1
<class 'int'>
ali
<class 'str'>
7.8
<class 'float'>


In [15]:
list2=[34,56,23,77]

In [17]:
sum(list2)

190

In [19]:
list2.append(8)

In [21]:
list2

[34, 56, 23, 77, 8]

In [23]:
list2.extend([56,7,8,9])

In [25]:
list2

[34, 56, 23, 77, 8, 56, 7, 8, 9]

In [29]:
list2.sort()

In [33]:
list2

[7, 8, 8, 9, 23, 34, 56, 56, 77]

In [35]:
list2.index(56)

6

In [37]:
list2[6]

56

In [45]:
list2.remove(8)
list2

[7, 23, 34, 56, 56, 77]

In [49]:
min(list2)

7

In [51]:
max(list2)

77

In [66]:
import numpy as np

In [106]:
l1=[2, "ahmed", 7.8]
l1=np.array(l1)
print(l1)

['2' 'ahmed' '7.8']


In [74]:
for i in l1:
    print(i)
    print(type(i))

2
<class 'numpy.str_'>
ahmed
<class 'numpy.str_'>
7.8
<class 'numpy.str_'>


In [104]:
l1=[2, 6.7, 7.8]
l1=np.array(l1)

In [78]:
for i in l1:
    print(i)
    print(type(i))

2.0
<class 'numpy.float64'>
6.7
<class 'numpy.float64'>
7.8
<class 'numpy.float64'>


In [92]:
l1=[1,3,5]
l2=[6,7,8]

print(l1+l2)

[1, 3, 5, 6, 7, 8]


In [82]:
arr1=np.array([2,3,4])
arr2=np.array([4,5,6])

print(arr1+arr2)

[ 6  8 10]


In [84]:
([3,4,5,6,7,8])

[3, 4, 5, 6, 7, 8]

In [88]:
array2d=np.array([[1,2,3],
                 [12,45,5]])

In [90]:
array2d.shape

(2, 3)

In [177]:
array1d=np.array([1,2,3,4,5,8])
array1d.shape

(6,)

In [179]:
array1d[2:5]
#1st argument inclusive, 2nd exclusive


array([3, 4, 5])

In [111]:
array1d.ndim

1

In [113]:
array2d.ndim

2

In [181]:
arr=np.array([[1,2,3],
             [2,3,4],
             [3,4,5]])

In [117]:
arr[0]

array([1, 2, 3])

In [183]:
arr.transpose()

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [119]:
arr[0][0]

1

In [121]:
np.sum(arr)

27

In [123]:
np.mean(arr)

3.0

In [125]:
np.median(arr)

3.0

In [129]:
np.std(arr)

1.1547005383792515

In [131]:
import pandas as pd

In [135]:
df=pd.read_excel("D:\\test.xlsx")

In [137]:
df

name  marks   age
0       Ali   45.0  23.0
1     Ahmed  100.0  12.0
2    Rameen   34.0  34.0
3    Ayesha   23.0   0.0
4   Khadija    NaN  42.0
5    saleem   78.0   NaN
6     rehan   98.0  12.0
7    daneen   22.5  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0

In [143]:
df.head(7)

name  marks   age
0      Ali   45.0  23.0
1    Ahmed  100.0  12.0
2   Rameen   34.0  34.0
3   Ayesha   23.0   0.0
4  Khadija    NaN  42.0
5   saleem   78.0   NaN
6    rehan   98.0  12.0

In [141]:
df.tail()

name  marks   age
5    saleem   78.0   NaN
6     rehan   98.0  12.0
7    daneen   22.5  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0

In [145]:
df=pd.read_excel("test.xlsx")

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    10 non-null     object 
 1   marks   9 non-null      float64
 2   age     9 non-null      float64
dtypes: float64(2), object(1)
memory usage: 372.0+ bytes


In [149]:
df.describe()

marks        age
count    9.000000   9.000000
mean    50.777778  20.000000
std     32.329467  14.739403
min     22.000000   0.000000
25%     23.000000  12.000000
50%     34.000000  21.000000
75%     78.000000  34.000000
max    100.000000  42.000000

In [157]:
df.columns

Index(['name', 'marks', 'age'], dtype='object')

In [161]:
df.dtypes

name      object
marks    float64
age      float64
dtype: object

In [163]:
df.isnull

<bound method DataFrame.isnull of        name  marks   age
0       Ali   45.0  23.0
1     Ahmed  100.0  12.0
2    Rameen   34.0  34.0
3    Ayesha   23.0   0.0
4   Khadija    NaN  42.0
5    saleem   78.0   NaN
6     rehan   98.0  12.0
7    daneen   22.0  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0>

In [165]:
df=df.dropna()
#df.dropna(inplace=True)

In [167]:
df.isnull

<bound method DataFrame.isnull of        name  marks   age
0       Ali   45.0  23.0
1     Ahmed  100.0  12.0
2    Rameen   34.0  34.0
3    Ayesha   23.0   0.0
6     rehan   98.0  12.0
7    daneen   22.0  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0>

In [169]:
df.fillna(0)

name  marks   age
0       Ali   45.0  23.0
1     Ahmed  100.0  12.0
2    Rameen   34.0  34.0
3    Ayesha   23.0   0.0
6     rehan   98.0  12.0
7    daneen   22.0  34.0
8   zawiyar   34.0   2.0
9  abdullah   23.0  21.0

In [173]:
df["marks"].shape

(8,)

In [175]:
for i in df["marks"]:
    print(i)

45.0
100.0
34.0
23.0
98.0
22.0
34.0
23.0


In [185]:
4==3

False

In [187]:
int(4==3)

0

In [189]:
np.linspace(1, 100, 100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])